# Generated by Django 3.0.7 on 2020-06-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20200610_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='lection',
            name='photo',
            field=models.ImageField(default=0, upload_to='App/static/lections'),
        ),
        migrations.AlterField(
            model_name='lection',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Название лекции'),
        ),
        migrations.AlterField(
            model_name='lection',
            name='short_description',
            field=models.CharField(max_length=70, verbose_name='Очень краткое описание лекции'),
        ),
    ]
