# Generated by Django 3.0.7 on 2020-06-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20200612_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='lection',
            name='audio',
            field=models.FileField(default=0, upload_to='lections/audios', verbose_name='Аудио к лекции'),
        ),
        migrations.AlterField(
            model_name='lection',
            name='photo',
            field=models.ImageField(default=0, upload_to='lections/images', verbose_name='Изображение к лекции'),
        ),
    ]
