# Generated by Django 3.0.7 on 2020-06-16 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20200612_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lection',
            old_name='short_description',
            new_name='long_description',
        ),
    ]
