# Generated by Django 3.0.7 on 2020-06-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20200616_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lection',
            name='long_description',
            field=models.TextField(verbose_name='Описание(уже подлиннее)'),
        ),
    ]
