# Generated by Django 3.0.7 on 2020-06-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
